[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600

lib_deps = 
    adafruit/Adafruit TCS34725@^1.4.4
<<<<<<< Updated upstream
    adafruit/Adafruit BNO055 @ ^1.6.4 
=======
    https://github.com/zischknall/BohleBots_BNO055.git
>>>>>>> Stashed changes
